name: "CI"
on: ["push", "pull_request"]

jobs:
  ios:
    name: "Build iOS - OTP ${{ matrix.otp }}"
    runs-on: "macos-latest"
    strategy:
      matrix:
        otp: ["26", "27", "28"]
        elixir: ["1.19.0"]
    steps:
    - run: brew install git carthage coreutils
    - uses: actions/checkout@v5

    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.elixir }}
        otp-version: ${{ matrix.otp }}

    - name: Build runtime
      run:  |
        OTP_TAG=${{ steps.setup-beam.otp-version }} ELIXIR_VERSION=${{ steps.setup-beam.elixir-version }} mix package.ios.runtime

    - name: Archive runtimes
      uses: actions/upload-artifact@v4
      with:
        name: ios-otp${{ steps.setup-beam.otp-version }}-elixir${{ steps.setup-beam.elixir-version }}
        path: _build/liberlang-otp*.xcframework
