name: "CI"
on: ["push", "pull_request"]
env:
  OTP_SOURCE: https://github.com/erlang/otp

jobs:
  build:
    name: "Build Android ${{ matrix.arch }} - OTP ${{ matrix.otp_version }}"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        arch: ["arm", "arm64", "x86_64"]
        otp_version: ["28.1", "27.3"]
        elixir_version: ["1.19.0", "1.18.0"]
        exclude:
          # Exclude incompatible combinations
          - otp_version: "27.3"
            elixir_version: "1.19.0"
    steps:
    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        elixir-version: ${{ matrix.elixir_version }}

    - uses: actions/checkout@v4

    - run: |
        ELIXIR_VERSION=${{ matrix.elixir_version }} scripts/install_elixir.sh "$HOME/elixir"
        echo "$HOME/elixir/bin" >> $GITHUB_PATH

    - name: Build Android ${{ matrix.arch }} runtimes
      run: |
        mix deps.get
        ARCH=${{ matrix.arch }} OTP_TAG=OTP-${{ matrix.otp_version }} ELIXIR_VERSION=${{ matrix.elixir_version }} mix package.android.runtime
    - name: Archive Android runtimes
      uses: actions/upload-artifact@v4
      with:
        name: android-${{ matrix.arch }}-otp${{ matrix.otp_version }}-elixir${{ matrix.elixir_version }}
        path: _build/android-runtime-otp*.zip
    - name: Android ${{ matrix.arch }} release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: _build/android-runtime-otp*.zip

  ios:
    name: "Build iOS - OTP ${{ matrix.otp_version }}"
    runs-on: "macos-latest"
    strategy:
      matrix:
        otp_version: ["28.1", "27.3"]
        elixir_version: ["1.19.0", "1.18.0"]
        exclude:
          # Exclude incompatible combinations
          - otp_version: "27.3"
            elixir_version: "1.19.0"
    steps:
    - run: brew install git carthage coreutils
    - uses: actions/checkout@v4

    - name: Setup elixir
      run: |
        git clone https://github.com/asdf-vm/asdf.git ~/.asdf
        . $HOME/.asdf/asdf.sh
        asdf plugin add erlang
        asdf plugin add elixir
        echo "erlang ${{ matrix.otp_version }}" >> .tool-versions
        echo "elixir ${{ matrix.elixir_version }}-otp-$(echo ${{ matrix.otp_version }} | cut -d. -f1)" >> .tool-versions
        asdf install

    - name: Build runtime
      run:  |
        . $HOME/.asdf/asdf.sh
        OTP_TAG=OTP-${{ matrix.otp_version }} ELIXIR_VERSION=${{ matrix.elixir_version }} mix package.ios.runtime

    - name: Archive runtimes
      uses: actions/upload-artifact@v4
      with:
        name: ios-otp${{ matrix.otp_version }}-elixir${{ matrix.elixir_version }}
        path: _build/liberlang-otp*.xcframework

    - name: iOS release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: _build/liberlang-otp*.xcframework
